### PR TITLE
fix(access) adding removed headers works as expected

### LINKED ISSUE #4950: Request-Transformer remove Authorization Header and add it no logger works
### Summary

If you configure a plugin like this:

```
curl -X POST http://kong:8001/services/{service}/plugins \
    --data "name=request-transformer"  \
    --data "config.remove.headers=Authorization" \
    --data "config.add.headers=Authorization:Basic test" 
```

And send a request like this:

curl --request POST \
  --url https://kong/test \
  --header 'authorization: Basic dGVzdDp0ZXN0' \
  --header 'content-type: application/json' \
  --data '{}'

The Authorization Header the upstream is without Authorization.

Replace works fine. But if you request like:

curl --request POST \
  --url https://kong/test \
  --header 'content-type: application/json' \
  --data '{}'

Replace is no option.

I like to remove the Authorization Header if existing and add a new Authorization-Header.

Only add doesnt work if there is already a Authorization-Header than i get two with different values.

We update from 0.13 to 1.2

With 0.13 this works fine, after the update this no longer works it seems as replace executed after add.

### PR DESCRIPTION
**Pull request by locao**
- fixed bug on adding a header with the same name as a removed one.
- plugin now uses PDK
- version bumped

FIX Kong/kong#4950

### CODE REVIEW

File: kong/plugins/request-transformer/access.lua [hunk 1]
```diff
@@ -416,7 +426,7 @@ local function transform_multipart_body(conf, body, content_length, content_type
 end
 
 local function transform_body(conf)
-  local content_type_value = req_get_headers()[CONTENT_TYPE]
+  local content_type_value = get_headers()[CONTENT_TYPE]
```
Comment (bungle) [inline kong/plugins/request-transformer/access.lua]: there is `get_header(CONTENT_TYPE)` in `pdk` which could be better fit here.

File: kong/plugins/request-transformer/access.lua [hunk 2]
```diff
@@ -439,31 +448,30 @@ local function transform_body(conf)
...
   end
 end
 
 local function transform_method(conf)
   if conf.http_method then
-    req_set_method(ngx["HTTP_" .. conf.http_method:upper()])
+    set_method(conf.http_method:upper())
     if conf.http_method == "GET" or conf.http_method == "HEAD" or conf.http_method == "TRACE" then
-      local content_type_value = req_get_headers()[CONTENT_TYPE]
+      local content_type_value = get_headers()[CONTENT_TYPE]
```
Comment (bungle) [inline kong/plugins/request-transformer/access.lua]: Ditto.

File: kong/plugins/request-transformer/access.lua [hunk 3]
```diff
@@ -439,31 +448,30 @@ local function transform_body(conf)
...
-        req_read_body()
-        local body = req_get_body_data()
+        local body = get_raw_body()
         local parameters = decode_args(body)
 
         -- Append to querystring
-        local querystring = req_get_uri_args()
+        local querystring = get_uri_args()
         for name, value in pairs(parameters) do
           querystring[name] = value
```
Comment (bungle) [inline kong/plugins/request-transformer/access.lua]: Do we want `append` or `add or replace`? This seems to replace existing. Also PDK has `add_header` for `append`?

File: kong/plugins/request-transformer/handler.lua [hunk 4]
```diff
@@ -1,15 +1,18 @@
+local BasePlugin = require "kong.plugins.base_plugin"
```
Comment (kikito) [inline kong/plugins/request-transformer/handler.lua]: BasePlugin is about to be deprecated. We should not be extending it

File: kong/plugins/request-transformer/handler.lua [hunk 5]
```diff
@@ -1,15 +1,18 @@
...
 local access = require "kong.plugins.request-transformer.access"
 
+local RequestTransformerHandler = BasePlugin:extend()
 
-local RequestTransformerHandler = {
-  VERSION  = "1.2.2",
-  PRIORITY = 801,
-}
-
+function RequestTransformerHandler:new()
```
Comment (kikito) [inline kong/plugins/request-transformer/handler.lua]: We should not be calling `new` either. It is not used any more.

File: kong/plugins/request-transformer/handler.lua [hunk 6]
```diff
@@ -1,15 +1,18 @@
...
+  RequestTransformerHandler.super.new(self, "request-transformer")
+end
 
 function RequestTransformerHandler:access(conf)
+  RequestTransformerHandler.super.access(self)
```
Comment (kikito) [inline kong/plugins/request-transformer/handler.lua]: Calling `super` like this is also not needed any more (you can remove this line)

File: kong/plugins/request-transformer/handler.lua [hunk 7]
```diff
@@ -1,15 +1,18 @@
+local BasePlugin = require "kong.plugins.base_plugin"
 local access = require "kong.plugins.request-transformer.access"
 
+local RequestTransformerHandler = BasePlugin:extend()
```
Comment (kikito) [inline kong/plugins/request-transformer/handler.lua]: Make it a simple empty table instead: `RequestTransformerHandler = {}`.

Alternatively, make it a table with the `PRIORITY` and `VERSION` fields set inside.

**Review by kikito — CHANGES_REQUESTED** [review]

**Review by kikito — APPROVED** [review]

File: kong-plugin-request-transformer-1.3.0-0.rockspec [hunk 8]
```diff
@@ -1,9 +1,9 @@
 package = "kong-plugin-request-transformer"
-version = "1.2.2-0"
+version = "1.3.0-0"
```
Comment (kikito) [inline kong-plugin-request-transformer-1.3.0-0.rockspec:2]: Since this is a bugfix, and it its not adding a feature, the "proper" version to use here would be `"1.2.3-0"`

This has a nice effect: it makes https://github.com/Kong/kong/pull/5119 not needed (the `~> 1.2` will take the latest which is not backwards compatible)

**Review by kikito — CHANGES_REQUESTED** [review]

File: kong-plugin-request-transformer-1.3.0-0.rockspec (hunk 8 above)
Comment (hishamhm) [reply kong-plugin-request-transformer-1.3.0-0.rockspec:2]: This was merged as 1.3.0, right? So it does need the Kong PR for the version bump

Comment (locao) [reply kong-plugin-request-transformer-1.3.0-0.rockspec:2]: @hishamhm I just reverted this, opened a new PR as 1.2.3, and closed the PR on Kong for the version bump.
