### PR TITLE
fix(access) keep configured name case on append/add headers

### LINKED ISSUE #28: Header name is lowercased when adding header
Hi, after upgrading Kong 1.2.1 -> 2.3.1 I noticed that the the request transformer plugin is passing on header names in lowercase to upstream services. 
This was particularly the case when using: `config.add.headers`. 

Because our upstream service depends on the case sensitivity of header names, all requests stopped working.
As a workaround we have switched over to using: `config.append.headers`, which does not exhibit the same behavior of lowercasing header names.

After digging through previous commits, I noticed that this change was committed on Oct 14, 2019: [https://github.com/Kong/kong-plugin-request-transformer/commit/9d3c2411c4359cf6bd2881ba82c896e977642a9b#diff-bac2d4423c364b627847836d9826aef7R212](commit)

In order to fix this issue, I could imagine that:
```lua
    name = name:lower()
    if not headers[name] and name ~= HOST then
      headers[name] = value
    end
```

would have to be changed to:
```lua
    if not headers[name] and name:lower() ~= HOST then
      headers[name] = value
    end
```

### PR DESCRIPTION
**Pull request by locao**
Fix: #28

### CODE REVIEW

**Comment by ghost** [comment]
Hi vinicius, would it be possible to cherry-pick this into the EE plugin?

File: kong/plugins/request-transformer/access.lua [hunk 1]
```diff
@@ -212,15 +212,24 @@ local function transform_headers(conf)
...
+      if headers[name] ~= nil then -- keep original content, use configd case
+        for header_name, _ in pairs(headers) do
+          if name:lower() == header_name:lower() then
+            local content = headers[header_name]
+            headers[header_name] = nil
+            headers[name] = content
+            break
+          end
+        end
+      end
```
Comment (dndx) [inline kong/plugins/request-transformer/access.lua]: Do we need this change? From the descriptions of https://github.com/Kong/kong-plugin-request-transformer/issues/28 it seems that only `add.headers` has the issue and `append.headers` does not lower case the headers anyway.

Comment (locao) [reply kong/plugins/request-transformer/access.lua]: We can leave this change out, but my approach here was to keep the same behavior that we'd get with the `add.headers`, i.e. force the configured case to be used.

File: kong/plugins/request-transformer/access.lua [hunk 2]
```diff
@@ -212,15 +212,24 @@ local function transform_headers(conf)
...
       headers[name] = append_value(headers[name], value)
     end
   end
```
Comment (dndx) [inline kong/plugins/request-transformer/access.lua]: I see, how about this version? I tested it locally and it seems to work well.

What we are doing here is to avoid a O(n^2) situation when checking the `headers` table for duplicates. Since `get_headers` always return request headers in all lower case, we can do a single lookup instead of loops to avoid this extra looping (especially considering `pairs` is not JITable and known to be slow).
```suggestion
  for _, name, value in iter(conf.append.headers) do
    local name_lc = name:lower()

    if name_lc ~= HOST and name ~= name_lc and headers[name] ~= nil then
      -- keep original content, use configd case
      headers[name] = headers[name_lc]
      headers[name_lc] = nil
    end

    headers[name] = append_value(headers[name], value)
  end
```

File: kong/plugins/request-transformer/access.lua (hunk 1 above)
Comment (dndx) [reply kong/plugins/request-transformer/access.lua]: See comment below.
